# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:10.9
      
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/soymicheltWebApp

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: Instalación de Paquetes NPM
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Instalación de Firebase-Tools
          command: npm install -g firebase-tools
        
      # run tests!
      - run:
          name: Ejecución de Tests
          command: npm test

      - run:
          name: Estableciendo Firebase en Default
          command: firebase use default

      - run:
          name: Haciendo Deploy de la App en Firebase
          command: firebase deploy --token $SOYMICHELT_FIREBASE_TOKEN --non-interactive